### PR TITLE
WIP: JSXTransformer

### PR DESCRIPTION
**Pull request by danmartinez101**

### CODE REVIEW

**Comment by danmartinez101** [comment]
This is just a quick first pass but wanted to put it up for early feedback. 

Some related things to consider: 
Is this just JSXTransformer or is it a more generic babel browser build?
If this is a generic babel browser build, should we add a feature whereby consumers may configure plugins/presets/etc via attributes on the script tag or a similar mechanism?

**Comment by danmartinez101** [comment]
@zpao Does this address the concerns you mentioned in https://github.com/facebook/react/issues/5497 ? 

@Daniel15 I'm going to be busy the next couple of weeks so I won't be able to do much more with this in the short term. Would you prefer I close it or leave it open in case someone else is interested in building on it? I'm happy to add whoever as a contributor so they can extend the PR if desired.

**Comment by zpao** [comment]
No idea how what RX does with order so I can't really say. Bring in "async" scripts and it's a bit more to worry about. Also, RX seems like it's probably a really heavy dependency (though haven't looked and not sure how much it actually since this is a dev tool).

**Comment by Daniel15** [comment]
Yeah, Rx seems pretty heavy for something like this.

I think ideally it wouldn't be specific to JSX, and you could provide the plugins inline in the script tag if wanted

```
<script type="text/babel" data-plugins="stage2,react">
```

**Pull request closed without merging**
