### PR TITLE
Update Babel presets

### PR DESCRIPTION
**Pull request by taion**
- Explicitly bump versions in package.json
- Add back CJS module transform to es2015-loose
- Sync up es2015-loose with es2015

cc @hzoo – right now the `es2015-loose` setting on the Babel REPL page doesn't transpile ES modules at all, which doesn't match the actual behavior of `babel-preset-es2015-loose`. That's the only material change here; the rest is just a bit of housekeeping.

### CODE REVIEW

**Comment by Daniel15** [comment]
I want to keep a preset that does not do any compilation of CommonJS
modules. Maybe I should give that a different name?

**Comment by taion** [comment]
You have one, I think – `es2015-no-commonjs`: https://github.com/Daniel15/babel-standalone/blob/release-6.10.3/src/index.js#L145.

Though the npm equivalents would be either `es2015-native-modules` or `es2015-webpack`, and `es2015-loose-native-modules` for the loose version.

**Comment by Daniel15** [comment]
I think what I actually want is `es2015-loose-no-commonjs`, but I can add that separately :stuck_out_tongue:

**Comment by taion** [comment]
The npm package with that preset has the unfortunate name of `babel-preset-es2015-loose-native-modules`. Or worse, `babel-preset-es2015-webpack-loose`.

**Comment by Daniel15** [comment]
> babel-preset-es2015-**webpack**-loose.

ಠ_ಠ

**Comment by taion** [comment]
Yup. And for the non-loose one, you have your choice of `babel-preset-es2015-native-modules` and `babel-preset-es2015-webpack`. And the latter is over 3x as popular on npm. ¯\_(ツ)_/¯

Also note that the loose versions don't even consistently put the "loose" modifier in the same place in the package name.

**Comment by hzoo** [comment]
Unfortunate and probably why we need an "official" loose preset, etc. https://github.com/babel/babel/pull/3331 should solve most of the issues

**Comment by hzoo** [comment]
Ok we have ^ now https://github.com/babel/babel/releases/tag/v6.13.0

**Comment by Daniel15** [comment]
Cool, I'll check it out! How are the options specified - Are they just passed to the `Babel.transform` call?

**Comment by Daniel15** [comment]
Let's move the discussion to #46 :+1:

**Pull request merged**
